source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CZPicker_Example', :exclusive => true do
  pod "CZPicker", :path => "../"
end

target 'CZPicker_Tests', :exclusive => true do
  pod "CZPicker", :path => "../"
end
