source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'CZPicker_Example', :exclusive => true do
  pod "CZPicker", :path => "../"
end

target 'CZPicker_Tests', :exclusive => true do
  pod "CZPicker", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
